### PR TITLE
fix: promisify overriding a param that is not configurable on iOS 10

### PR DESCRIPTION
**Pull request by andrejborstnik**
Affects iOS 10 & early iOS 11 versions
Screenshot 2020-10-31 at 18 41 25

### CODE REVIEW

**Review by ChALkeR — DISMISSED** [review]
Likely, `src/types/util.promisify.d.ts` and the `util.promisify` dependency should be removed (with `yarn.lock` updated).

See how those were introduced in 6abe24aa9c740b11a56c6b031e9359a2219f9757.

**Comment by andrejborstnik** [comment]
> Likely, `src/types/util.promisify.d.ts` and the `util.promisify` dependency should be removed (with `yarn.lock` updated).
> 
> See how those were introduced in [6abe24a](https://github.com/ExodusMovement/hedera-sdk-js/commit/6abe24aa9c740b11a56c6b031e9359a2219f9757).

@ChALkeR I saw it is used in other places in node code, that is why I didn't remove it. We can change that as well, but my goal right now is to fix mobile in prod

**Comment by ChALkeR** [comment]
@andrejborstnik index-node.js uses native `require('util').promisify`, not the `require('util.promisify')` module.

**Comment by andrejborstnik** [comment]
> @andrejborstnik `index-node.js` uses native `require('util').promisify`, not the `require('util.promisify')` module.

You are right, my bad. Will remove the dep

**Comment by andrejborstnik** [comment]
@ChALkeR removed the explicit dep, but it is still there as a sub-dep (was before https://github.com/ExodusMovement/hedera-sdk-js/commit/6abe24aa9c740b11a56c6b031e9359a2219f9757 as well)

**Review by ChALkeR — APPROVED** [review]
utACK.

**Comment by ChALkeR** [comment]
Typescript compilation failed on this one, will fix in a separate commit.
